### ISSUE TITLE
Add the ability to get the interface addresses of a Domain (VM)

### ISSUE THREAD

**Issue by jessecooper** [ansible-collections/community.libvirt#124]
##### SUMMARY
I do not see this implemented, documented or discussed anywhere so, I am created this feature request with the good intention of implementing it if the feature is not already available.

I would like to be able to get the Interfaces Addresses of a Domain (VM).
  
virsh command:
`virsh domifaddr --source <agent|arp|lease> <vm_name>`
##### ISSUE TYPE
- The idea of this feature would comes from wanting to get the IP address of an interface of a VM that has just been deployed to continue the VMs OS setup. 

##### COMPONENT NAME
It seems the best place for this feature would be in the `virt` module.  The `VM_COMMAND` could be `get_ifaddresses`.

##### ADDITIONAL INFORMATION

This module would be used to get the Domain (VM) interface addresses.
Example code using [libvirt-python](https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Network_Interface-Addresses.html) 

```yaml
- name: vm info
   community.libvirt.virt:
     command: get_ifaddresses
     source: <agent|arp|lease>
     domain: <name_of_vm>
   register: ifaddresses
```
