### ISSUE TITLE
Command not found when executing in VM

### ISSUE THREAD

**Issue by gabrik** [ansible-collections/community.libvirt#138]
##### SUMMARY
Trying to run a command on the VM results in `command not found`
The command is actually there, when connecting via serial or SSH it can be executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
libvirt_quemu

##### ANSIBLE VERSION
```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ato/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ato/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ato/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ato/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/ato/.local/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.libvirt 1.2.0

# /home/ato/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.libvirt 1.2.0
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
Ansible machine:
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
VM:
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

##### STEPS TO REPRODUCE
Run the playbook and it will fail

```yaml
---
- name: Install cargo and tools
  hosts: "{{ host | default('vms') }}"
  tasks:
    - name: Install prerequisites
      become: true
      apt:
        pkg:
          - build-essential
          - clang
          - libclang-dev
          - git

    - name: check if cargo is installed
      shell: |
        export HOME=/root/
        . /root/.bashrc
        command -v cargo
      args:
        executable: /bin/bash
      register: cargo_exists
      ignore_errors: yes

    - name: check if cargo-deb is installed
      shell: |
        export HOME=/root/
        . /root/.profile
        command -v cargo-deb
      args:
        executable: /bin/bash
      register: cargo_deb_exists
      ignore_errors: yes
    - name: Download rust installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: '0755'
        force: 'yes'


    - name: Install rust toolchain
      when: cargo_exists is failed
      shell: /tmp/rustup.sh -y
      args:
        executable: /bin/bash

    - name: Install rust tools
      when: cargo_deb_exists is failed
      shell: |
        export HOME=/root/
        . /root/.bashrc
        cargo install cargo-deb
      args:
        executable: /bin/bash
```

##### EXPECTED RESULTS
Installation of rust toolchain and cargo-deb to be successful 

##### ACTUAL RESULTS
Fails when installing cargo-deb,
The same playbook runs well in an LXD container of bare-metal
The actual verbose output can be found here: https://gist.github.com/gabrik/0adecd283d4dc426b497f524fff764c0#file-gistfile1-log
