### ISSUE TITLE
Clone VM

### ISSUE THREAD

**Issue by x09** [ansible-collections/community.libvirt#148]
##### SUMMARY
Clone VM functionality

##### ISSUE TYPE
I have few VM as templates (Server OS, Desktop OS, etc).
if necessary, I clone the original (source) VM and work in its replica (destination).
If I need to create a test bench from 1 server and 5 desktop machines, 2 source (as template) VMs are enough for me.
I just clone from them.

I want work with it via ansible, but have not.

##### COMPONENT NAME
(https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_module.html)

##### ADDITIONAL INFORMATION

I suggest add new command, something like 

```yaml
- name: Clone VM
  community.libvirt.virt:
    command: clone
    source_name: vm01_srv_template
    dest_name:  dns_server_01
       dest_pool:  'new_pool_name_if_defined'
```
