### ISSUE TITLE
FR: Return Interfaces and Macs for Domains that are powered off

### ISSUE THREAD

**Issue by stratus-ss** [ansible-collections/community.libvirt#189]
##### SUMMARY
There are use cases where you need to get the mac address of a domain in order to provide it to PXE, Sushy-tools or other related tools. There should be a way to get this information without powering on the machine

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`get_interfaces` will be apart of `virt.py`

##### ADDITIONAL INFORMATION

Call this playbook and a dict called "network_interfaces" is created that you can use for various automation tasks

```yaml
---
- name: get UUID
  gather_facts: false
  hosts: localhost
  tasks:
  - name: register vm info
    community.libvirt.virt:
      command: get_interfaces
      name: "sno"
    register: vminfo

  - name: debug result
    debug: 
      msg: "{{ vminfo }}"


```

Sample output

```
TASK [debug result] **************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "network_interfaces": {
            "bridge-f0": "52:54:00:c1:45:c9",
            "bridge0-f1": "52:54:00:00:8d:3b"
        }
    }
}
```
