### ISSUE TITLE
Update of libvirt network default fails

### ISSUE THREAD

**Issue by simsiem** [ansible-collections/community.libvirt#47]
##### SUMMARY
I want to update the default network of libvirt (purpose: add IPv6). Ansible reports that no change is necessary: `ok: [localhost]`, although the XML definition is different from what I get from `sudo virsh net-dumpxml default`.

If I change the _name_ in the ansible code but not in the XML definition, the default network gets updated as wanted.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.libvirt.virt_net

##### ANSIBLE VERSION

```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/walter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION

```paste below
empty output, no change.
```

##### OS / ENVIRONMENT

Fedora 32 (Workstation Edition)

##### STEPS TO REPRODUCE

(1) Create a new file _network_default.xml_ with the current XML definition of the default network.
```
sudo virsh net-dumpxml default
```
Modify the file.

(2) Run an ansible playbook containing the tasks:
```yaml
    - name: Network default is inactive
      community.libvirt.virt_net:
        state: inactive
        name: default
    - name: Default network defined correctly
      community.libvirt.virt_net:
        command: define
        name: default
        xml: '{{ lookup("template", "network_default.xml") }}'
```

Ansible reports that no change is necessary: `ok: [localhost]`, although the XML definition is different from what I get from `sudo virsh net-dumpxml default`.

(3) Change the name of the network in the playbook but not in the _network_default.xml_.
```yaml
    - name: Network default is inactive
      community.libvirt.virt_net:
        state: inactive
        name: default
    - name: Default network defined correctly
      community.libvirt.virt_net:
        command: define
        name: xyz
        xml: '{{ lookup("template", "network_default.xml") }}'
```
The default network gets updated as wanted. `sudo virsh net-dumpxml default` shows the change.

##### EXPECTED RESULTS
* Ansible can update the network _default_. 
* Most likely the network name should not be necessary in the playbook as it is already given in the XML file for the network definition.
