### ISSUE TITLE
virt state shutdown should wait till vm is at shutdown state

### ISSUE THREAD

**Issue by braindevices** [ansible-collections/community.libvirt#63]
##### SUMMARY

the virt state shutdown does not wait till the `virsh domstate` become `shut off`.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

virt
##### ANSIBLE VERSION

```paste below
2.10.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora33

##### STEPS TO REPRODUCE

```yaml
- name: list active vms
  virt:
    command: list_vms
    state: running
  register: vms_result
- debug:
    var: vms_result
- name: shutdown
  virt:
    state: shutdown
    name: "{{item}}"
  register: vm_shutdown_results
  loop:
    "{{vms_result.list_vms}}"
- debug:
    var: vm_shutdown_results
- name: list inactive vms
  virt:
    command: list_vms
    state: shutdown
  register: inactive_vms_result
- debug:
    var: inactive_vms_result
```

##### ACTUAL RESULTS

inactive_vms_result does not show all the VMs, most VMs are still at `in shutdown` state.

```paste below

```
